import torch
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset, concatenate_datasets
import re

# Setting up the model ID as the instruct variation of the 360M SmolLM
model_id = "HuggingFaceTB/SmolLM2-360M-Instruct"

# Bringing in the associated tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Loading in the model, turning on hidden states for later embedding extraction
# leaving device_map to auto so the weight allocation is automatic
# Setting to half precision to use less vram
model = AutoModelForCausalLM.from_pretrained(
    model_id, device_map="auto", dtype=torch.float16, output_hidden_states=True
)

# This dataset only has 1k entries, so after loading it in, im going to 
# merge the test,validation, and train just for label creation
# will need to split in my own way later on
ds = load_dataset("mbpp")
dataset = concatenate_datasets([ds['train'], ds['test'], ds['validation']])

# function to test the code created by the slm
def test_code(code_str):
    # if the code comes back blank return 0
    if not code_str.strip():
        return 0 
    try:
        # The terminal was hanging when input functions would run in the code that the 
        # slm would output. I can pass a dictionary to the exec function to rebind
        # what the input function will do when it runs in that context. Now it takes
        # any amount of arguments and always returns 1
        safe_env = {"input": lambda *args, **kwargs: "1"}
        exec(code_str, safe_env)
        # If the code doesn't crash return 1
        return 1
    except Exception:
        # else 0
        return 0

# This is a function to extract the code portion from the slm's response
# I set up the delimiter as suggested by Prof. Kristiadi 
def extract_code(text):
    # Using regex to grab all code instances (dotall so it doesnt stop at linebreak)
    matches = re.findall(r"\[CODE\](.*?)\[/CODE\]", text, re.DOTALL | re.IGNORECASE)
    if matches:
        return matches[0].strip()
    # Had some issues where the delimiter would be some traditionall language model
    # coding one so accounting for those as well. (```python)
    matches_md = re.findall(r"```(?:python)?(.*?)```", text, re.DOTALL | re.IGNORECASE)
    if matches_md:
        return matches_md[0].strip()
    # otherwise return a blank string
    return ""

# Setting up the arrays for the embeddings and their labels
embeddings = []
labels = []

# Enumerating through the dataset with a break at 1200 just in case i swap to a larger dataset
for i, item in enumerate(dataset):
    if i >= 1200: 
        break
        
    # The one data set used key 'text', while the other used key 'prompt',
    # it is currently set up for either
    prompt_text = item.get('prompt', item.get('text', ''))
    # Providing the instruction with the delimiter as recommended by Prof. Kristiadi
    instruction = f"You are a Python programmer. Write a Python script to solve the following problem. You MUST enclose your exact code between the delimiters [CODE] and [/CODE].\n\nProblem: {prompt_text}"
    
    # tokenizing the query with the pre-text attached, then sending it to the gpu
    inputs = tokenizer(instruction, return_tensors="pt").to(model.device)
    
    # Turning off computational graph generation / gradient tracking
    # as we are not training
    with torch.no_grad():
        # forward pass on that input
        outputs = model(**inputs)
        # Extract the hidden state of the last token of the prompt
        # moving it to the cpu so I can use the storage libraries on it
        # converting it to a numpy array from a pytorch tensor to use it with 
        # scikit learn in the following file
        # Storing as 32 bit instead of 64 bit because it's a huge quantity of dimensions
        # and may take up a lot of storage
        hidden_state = outputs.hidden_states[-1][0, -1, :].cpu().numpy().astype(np.float32)
        
        # Getting the SLM to generate tokens based on that query
        # currently capping its answer at 150 tokens, though may need to view its actual 
        # output and reconsider.
        generated_ids = model.generate(**inputs, max_new_tokens=150, pad_token_id=tokenizer.eos_token_id)
        
    # slicing off just the answer portion of the generated tokens
    generated_tokens = generated_ids[0][inputs.input_ids.shape[1]:]
    # Decoding it back into english
    generated_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
    
    # Using the extract code function on the english response generated by the slm
    code = extract_code(generated_text)
    # Seeing if the generated code runs successfully
    success = test_code(code)
    
    # Creating the data to train on, using the hidden state and its success
    embeddings.append(hidden_state)
    labels.append(success)
    

# Saving the embeddings and associated labels as numpy arrays
np.save("slm_embeddings.npy", np.array(embeddings))
np.save("execution_labels.npy", np.array(labels))
